{
    'name': 'Esis Logistique',
    "author": "Master Code",
    'application': True,
    "summary": "Réalisé dans le cadre de Hackaton",
    'depends': ['mail', 'web'],
    "data": [
        'security/ir.model.access.csv',
        'data/sequence.xml',
        'views/menu.xml',
        'views/materiel/enregistrement.xml',
        'views/materiel/allocation.xml',
        'views/materiel/categorie.xml',
        'views/demande/need.xml',
        'views/demande/request.xml',
        'views/materiel/modifier-materiel.xml',
    ],
    'qweb': [
        'view/*.xml',
    ],
    'auto_install': False,
    'installable': True,
    'post_init_hook': 'post_init_hook',
    'css': ['static/src/css/style.css'],
}